export const schema = {
  Team: {
    id: { type: "string" },
    teamCode: { type: "string" },
    address: { type: "string" },
    currentMomentum: { type: "integer" },
    momentumHistory: { type: "string" },
    totalSwaps: { type: "bigint" },
    totalVolume24h: { type: "bigint" },
    totalSupporters: { type: "integer" },
    priceChange24h: { type: "float" },
    lastUpdated: { type: "bigint" },
    createdAt: { type: "bigint" },
  },
  MomentumChange: {
    id: { type: "string" },
    teamAddress: { type: "string" },
    teamCode: { type: "string" },
    oldMomentum: { type: "integer" },
    newMomentum: { type: "integer" },
    momentumDelta: { type: "integer" },
    timestamp: { type: "bigint" },
    blockNumber: { type: "integer" },
    transactionHash: { type: "string" },
  },
  SupporterPoints: {
    id: { type: "string" },
    supporterAddress: { type: "string" },
    teamAddress: { type: "string" },
    teamCode: { type: "string" },
    pointsAwarded: { type: "bigint" },
    totalPoints: { type: "bigint" },
    timestamp: { type: "bigint" },
    blockNumber: { type: "integer" },
    transactionHash: { type: "string" },
  },
  Swap: {
    id: { type: "string" },
    teamAAddress: { type: "string" },
    teamACode: { type: "string" },
    teamBAddress: { type: "string" },
    teamBCode: { type: "string" },
    amount0In: { type: "bigint" },
    amount1In: { type: "bigint" },
    amount0Out: { type: "bigint" },
    amount1Out: { type: "bigint" },
    totalValue: { type: "bigint" },
    timestamp: { type: "bigint" },
    blockNumber: { type: "integer" },
    transactionHash: { type: "string" },
  },
  Supporter: {
    id: { type: "string" },
    address: { type: "string" },
    totalPoints: { type: "bigint" },
    favoriteTeam: { type: "string" },
    favoriteTeamAddress: { type: "string" },
    swapCount: { type: "integer" },
    lastSwapTime: { type: "bigint" },
    createdAt: { type: "bigint" },
    updatedAt: { type: "bigint" },
  },
  LeaderboardPosition: {
    id: { type: "string" },
    teamCode: { type: "string" },
    teamAddress: { type: "string" },
    rank: { type: "integer" },
    momentum: { type: "integer" },
    supporters: { type: "integer" },
    volume24h: { type: "bigint" },
    timestamp: { type: "bigint" },
  },
  HourlyStats: {
    id: { type: "string" },
    teamCode: { type: "string" },
    teamAddress: { type: "string" },
    hour: { type: "bigint" },
    startMomentum: { type: "integer" },
    endMomentum: { type: "integer" },
    swapCount: { type: "integer" },
    volumeIn: { type: "bigint" },
    volumeOut: { type: "bigint" },
    newSupporters: { type: "integer" },
  },
};
