export const schema = {
  Team: {
    id: "string",
    address: "string",
    currentMomentum: "integer",
    momentumHistory: "string",
    totalSwaps: "bigint",
    totalVolume24h: "bigint",
    totalSupporters: "integer",
    lastUpdated: "bigint",
    createdAt: "bigint",
  },
  MomentumChange: {
    id: "string",
    teamAddress: "string",
    oldMomentum: "integer",
    newMomentum: "integer",
    momentumDelta: "integer",
    timestamp: "bigint",
    blockNumber: "integer",
    transactionHash: "string",
  },
  SupporterPoints: {
    id: "string",
    supporterAddress: "string",
    teamAddress: "string",
    pointsAwarded: "bigint",
    totalPoints: "bigint",
    timestamp: "bigint",
    blockNumber: "integer",
    transactionHash: "string",
  },
  Swap: {
    id: "string",
    teamAAddress: "string",
    teamBAddress: "string",
    amount0In: "bigint",
    amount1In: "bigint",
    amount0Out: "bigint",
    amount1Out: "bigint",
    totalValue: "bigint",
    timestamp: "bigint",
    blockNumber: "integer",
    transactionHash: "string",
  },
  Supporter: {
    id: "string",
    address: "string",
    totalPoints: "bigint",
    favoriteTeamAddress: "string",
    swapCount: "integer",
    lastSwapTime: "bigint",
    createdAt: "bigint",
    updatedAt: "bigint",
  },
};
